#!/sbin/sh

OUTFD=/proc/self/fd/$2;
ZIP="$3";
DIR=`dirname "$ZIP"`;

ui_print() {
  until [ ! "$1" ]; do
    echo -e "ui_print $1\nui_print" > $OUTFD;
    shift;
  done;
}
show_progress() { echo "progress $1 $2" > $OUTFD; }
set_perm_recursive() {
  dirs=$(echo $* | awk '{ print substr($0, index($0,$5)) }');
  for i in $dirs; do
    chown -R $1.$2 $i; chown -R $1:$2 $i;
    find "$i" -type d -exec chmod $3 {} +;
    find "$i" -type f -exec chmod $4 {} +;
  done;
}
file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; }
abort() { ui_print "$*"; exit 1; }

mkdir -p /tmp/pb;
cd /tmp/pb;
unzip -o "$ZIP";
show_progress 0.1000000, 0;
ui_print "|-------------------------------------------|";
ui_print "|--------------PitchBlack TWRP--------------|";
ui_print "|-------------------v2.6--------------------|";
ui_print "|-----------For devicename----------|";
ui_print "|-------------------------------------------|";
ui_print "|           Based on TWRP v3.2.1-0          |";
ui_print "|-------------------------------------------|";
/sbin/busybox mount /system;
/sbin/sh /tmp/pb/flash_pb.sh;
ui_print "|-------------------------------------------|";
ui_print "|-------------------------------------------|";
ui_print "|-------------------------------------------|";
ui_print "|-------------------------------------------|";
ui_print "|                 Thank You                 |";
ui_print "|      Rebooting into PitchBlack TWRP       |";
ui_print "|-------------------------------------------|";
sleep 5s
show_progress 0.1000000, 90 ;
/sbin/unmount /system;
reboot recovery